### PR TITLE
Change Windows section in README.md

### PR DESCRIPTION
**Pull request by jboecker07**
This commit adds the Experimental Winget manifest option.

Current version in 0.6.5, will update to 0.7.0 when released.

#### **Description**
A brief description of what this pull request is

#### **Changes**
```diff
+ Added [via Winget: ```winget install LazapDevelopment.Lazap```]
- Removed [Download and Install the latest `.msi` file in the [releases](https://github.com/Lazap-Development/lazap/releases) section]
```

#### **Affected Operating System(s)**

Windows(8, 10, 11), Linux(Arch, Manjaro, etc.), MacOS

#### **Additional Information**

With Microsoft's recent annoucement of [Windows 10's End of Life](https://learn.microsoft.com/en-us/lifecycle/products/windows-10-home-and-pro), they are pushing people to install Windows 11, which has Winget preinstalled.

#### **Checklist**

- [x] Are the features of this PR completed?
- [x] Is the PR following the guidelines?

### CODE REVIEW

**Comment by p0ryae** [comment]
Thanks for adding lazap to winget. Although winget is a great cli version, I recommend modifying the READMe with both downloadable and winget options for more accessibility and user-preference.

**Comment by jboecker07** [comment]
Great point, updated it.

**Comment by p0ryae** [comment]
The winget you've added, does it update accordion to the latest release of lazap? Ensure that's the case so its efficient and hassle-free.

**Comment by jboecker07** [comment]
@p0ryae No it doesn't, it has to be manually updated and a new pull request will have to be created per release. But I'm marking this PR as open since Lazap is now in the Winget community repo.

**Pull request merged**
