### PR TITLE
Electron to Tauri, Future Release Candidate v0.4.0

### PR DESCRIPTION
**Pull request by DashCruft**
#### **Description**
Switching to Tauri has been very close to complete. The conversion is as close as identical but not complete yet. This PR is only getting merged if the Tauri version meets the nightly branch capability and quality. 

#### **Changes**
+ Full Rewrite of Storage System 
+ Partially re-wrote game detection system
+ Switched to Tauri, rust as backend
+ Other.

#### **Affected OS(es)**
All Supported Operating Systems.

### CODE REVIEW

**Comment by DashCruft** [comment]
Please avoid spamming @Baggette  

Thank you

**Comment by Baggette** [comment]
you’re no fun :(

**Comment by DashCruft** [comment]
> you’re no fun :(

I'm sorry but if you have comments feel free to do them. Just not spam a word constantly.

**Comment by Assassin-1234** [comment]
sexy

**Comment by DashCruft** [comment]
Merging to nightly

Everything is basically as functional as the nightly branch.

Removing the `tauri` branch also.

**Comment by Assassin-1234** [comment]
🎉

**Pull request merged**
