### PR TITLE
feat(app): Add auto-update feature to the app

### PR DESCRIPTION
**Pull request by LegItMate**
#### **Description**
This PR adds the long-awaited and previously removed auto-update feature through which the user gets notified of a new update and can easily update the app through in-built features! It is fully and well functioning on windows and with some differences on linux.

#### **Changes**
```diff
+ Added updater config
+ Made updater button functional
```

#### **Affected Operating System(s)**
* Windows
* Linux

#### **Additional Information**

In linux, the app does not update automatically and requires the user to update manually. Only a reminder is given to the user through the update button.

#### **Checklist**

- [x] Are the features of this PR completed?
- [x] Is the PR following the guidelines?

### CODE REVIEW

**Comment by p0ryae** [comment]
What's the state for this? Could you provide a small report?

**Comment by LegItMate** [comment]
The updater configuration and the updater button are fully functional and working with the current setup on my PC. You will only need to configure correctly building on your end, setup endpoint for update information and rest should function smoothly.

**Comment by p0ryae** [comment]
I'm guessing this is only functional on Windows. If not, please elaborate.

**Comment by LegItMate** [comment]
The additional information provided specifies it all.

Updating on Linux is still a mystery and I require you to test available options for managing auto-update to work flawlessly on linux as well as windows.

**Comment by p0ryae** [comment]
Everything looks great to me. 

Although, you're missing `TAURI_PRIVATE_KEY` environment variable, which will cause an error for the build. 
More information: https://tauri.app/v1/guides/distribution/updater/#signing-updates

**Comment by p0ryae** [comment]
Passing all checks, Functions as expected. 

As a reminder, the json file for endpoint is in the updater-endpoint branch.

**Pull request merged**
